<?php
require_once('./dao/carousel-dao.php');
require_once('./dao/titres-sections-dao.php');
require_once('./dao/background-dao.php');
require_once('./dao/activites-dao.php');
require_once('./dao/projets-dao.php');
require_once('./dao/videos-dao.php');
require_once('./dao/equipe-dao.php');
require_once('./dao/partenaires-dao.php');
require_once('./dao/documents-dao.php');
require_once('./dao/informations-dao.php');
require_once('./dao/reseauxsociaux-dao.php');
require_once('./dao/machines-dao.php');
require_once('./dao/admin-dao.php');
?>